[project]
name = "kim-bot"
version = "0.1.0"
description = "rag llm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.68.0",
    "langchain>=1.2.4",
    "ollama>=0.6.1",
]
